### ISSUE TITLE
non-verbatim interpolated string error

### ISSUE THREAD

**Issue by rswetnam** [KevinDockx/CSharp10DesignPatterns#1]
When I try to run the Factory Method on Abstract Factory I get the error:  

Error	CS8967	Newlines inside a non-verbatim interpolated string are not supported in C# 10.0. Please use language version preview or greater.	AbstractFactory	C:\repos\_Learning\Pluralsight\Dockx\C# 10 Design Patterns\Github\CSharp10DesignPatterns-main\Finished sample\AbstractFactory\Implementation.cs	117	Active

**Comment by KevinDockx** [comment]
Thanks for noticing, I just submitted a fix.  Enjoy the code/course! :)
